filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/transcendence/*.log
  json.keys_under_root: true
  json.add_error_key: true

processors:
  - add_fields:
      target: ''
      fields:
        environment: development
        application: transcendence

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
